-- =========================================================
-- Supabase SQL Editor에서 전체를 한 번에 붙여넣고 실행하세요.
-- (Supabase 프로젝트 → 왼쪽 메뉴 SQL Editor → New query → 붙여넣기 → Run)
-- =========================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- 1. 방명록(축하 메시지) 테이블 - 공개로 보고 쓸 수 있음
-- ---------------------------------------------------------
create table if not exists guestbook_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  tree_shape int not null default 0,
  created_at timestamptz not null default now()
);

-- 이미 이 테이블을 예전에 만들어서 쓰고 있었다면(나무 모양 기능 추가 전),
-- 아래 한 줄만 추가로 실행하면 기존 데이터는 그대로 두고 컬럼만 안전하게 추가됩니다.
alter table guestbook_messages add column if not exists tree_shape int not null default 0;

alter table guestbook_messages enable row level security;

create policy "guestbook public insert"
  on guestbook_messages for insert
  to anon
  with check ( char_length(name) <= 20 and char_length(message) <= 300 );

create policy "guestbook public select"
  on guestbook_messages for select
  to anon
  using ( true );

-- ⚠️ RLS 정책만으로는 부족합니다. Postgres 자체의 테이블 권한(GRANT)도 별도로 필요합니다.
-- 이 GRANT가 없으면 "permission denied for table ..." (42501) 오류가 납니다.
grant usage on schema public to anon;
grant select, insert on guestbook_messages to anon;

-- ---------------------------------------------------------
-- 2. 참석 여부(RSVP) 테이블 - 누구나 "쓰기"만 가능, "조회"는 불가
-- ---------------------------------------------------------
create table if not exists rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  side text not null check (side in ('groom', 'bride')),
  attend text not null check (attend in ('yes', 'no')),
  message text,
  created_at timestamptz not null default now()
);

-- 이미 위 테이블을 만든 적이 있다면(예전 버전) 아래 한 줄만 추가로 실행하면
-- 기존 테이블에 전화번호 컬럼이 안전하게 추가됩니다. (이미 있으면 아무 일도 안 함)
alter table rsvps add column if not exists phone text;

alter table rsvps enable row level security;

create policy "rsvp public insert"
  on rsvps for insert
  to anon
  with check ( char_length(name) <= 20 and (phone is null or char_length(phone) <= 20) );

-- 주의: select 정책을 만들지 않습니다.
-- RLS가 켜져 있고 select 정책이 없으면 anon은 절대 rsvps를 직접 조회할 수 없습니다.

-- 이 테이블도 마찬가지로 Postgres 테이블 권한(GRANT)이 필요합니다. (조회 권한은 주지 않음)
grant insert on rsvps to anon;

-- 두 테이블 모두 id가 자동 증가(identity) 컬럼이라, INSERT 시 내부적으로
-- 시퀀스 값을 가져오는 권한도 함께 있어야 합니다.
grant usage, select on all sequences in schema public to anon;

-- ---------------------------------------------------------
-- 3. 관리자 코드 저장 테이블 - anon 접근 완전 차단
-- ---------------------------------------------------------
create table if not exists admin_settings (
  id int primary key default 1,
  code_hash text not null
);

alter table admin_settings enable row level security;
-- 정책을 하나도 만들지 않습니다 = anon은 이 테이블에 절대 접근 불가.

-- 관리자 코드를 설정합니다. '0418' 부분을 원하는 코드로 바꿔서 실행하세요.
insert into admin_settings (id, code_hash)
values (1, crypt('0418', gen_salt('bf')))
on conflict (id) do update set code_hash = excluded.code_hash;

-- ---------------------------------------------------------
-- 4. 관리자 코드 검증 + RSVP 조회를 서버(Postgres) 안에서 함께 처리하는 함수
--    프론트엔드는 이 함수만 호출하고, 코드 비교는 절대 노출되지 않습니다.
-- ---------------------------------------------------------
create or replace function get_rsvps_with_code(input_code text)
returns setof rsvps
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from admin_settings
    where id = 1 and code_hash = crypt(input_code, code_hash)
  ) then
    return query select * from rsvps order by created_at asc;
  else
    raise exception 'invalid_code';
  end if;
end;
$$;

grant execute on function get_rsvps_with_code(text) to anon;

-- =========================================================
-- 나중에 관리자 코드를 바꾸고 싶다면 아래 한 줄만 다시 실행하면 됩니다.
-- update admin_settings set code_hash = crypt('새코드', gen_salt('bf')) where id = 1;
-- =========================================================
